### ISSUE TITLE
Add stylesheet

### ISSUE THREAD

**Issue by hello-smile6** [SpellCheckJS/html-client#6]
Currently, this is functional, but a bit bland. I'd like to use <a href="https://dreamcss.cf/">DreamCSS</a>. @MystPi Would you be okay with me using it?

**Comment by webdev03** [comment]
why not tailwind? or windicss

**Comment by hello-smile6** [comment]
> why not tailwind? or windicss

Release size. Also, the UI is pretty minimal right now. There's no point using a stylesheet that covers more than I use. Also, I like dreamcss. Just look at it!
<a href="https://github.com/MystPi/dreamcss/blob/8058a443d1dcd906f92970bddefd302b8ddbf307/src/dream.css#L66-L76">
```css
a {
  text-decoration: none;
  color: var(--text-color);
  border-bottom: 4px solid var(--link-color-1);
  -webkit-transition-property: background-color;
  -o-transition-property: background-color;
  transition-property: background-color;
  -webkit-transition-duration: var(--transition-duration);
       -o-transition-duration: var(--transition-duration);
          transition-duration: var(--transition-duration);
}
```
</a>
That has better browser support than most CSS frameworks.
